# Generated by Django 3.2.5 on 2021-10-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
